### PR TITLE
Fix/construction parse signed transaction fix

### LINKED ISSUE #250: Error when `/construction/parse` an already singed transaction
# Description

When executing `rosetta-cli check:construction` with staking operations it happens that there is an error when returning the [signers](https://github.com/input-output-hk/cardano-rosetta/blob/master/cardano-rosetta-server/src/server/services/cardano-services.ts#L781): We are grabbing the address from the `extraData` but staking operations don't need to provide the address so we are returning just `''`

# How to reproduce

Just execute 

```
rosetta-cli check:construction --configuration-file ./configuration/construction/delegation-configuration.json
``` 

on [this branch]() and you will get

```
Error: signer cannot be empty string: at index 1: /construction/parse: unable to parse signed transaction: unable to create transaction
```
# How to fix?

We need to generate the reward address if the operation to be parsed is a staking one and return that instead of `''`

### PR DESCRIPTION
**Pull request by jvieiro**
# Description

Adds the bech32 address as a return value in the `/construction/parse` endpoint when stake delegation, stake key deregistration, or withdrawal operations are included.

# References

Closes #250

### CODE REVIEW

**Review by tomasBustamante — APPROVED** [review]

File: cardano-rosetta-server/src/server/services/cardano-services.ts [hunk 1]
```diff
@@ -778,7 +788,7 @@ const configure = (linearFeeParameters: LinearFeeParameters, minKeyDeposit: numb
       const operations = parseOperationsFromTransactionBody(logger, parsed.body(), extraData, networkId);
       logger.info('[parseSignedTransaction] About to get signatures from parsed transaction');
       logger.info(operations, '[parseSignedTransaction] Returning operations');
-      const signers = extraData.map(data => data.account?.address || '');
+      const signers = getUniqueAddresses(extraData.map(data => getSignerFromOperation(logger, networkId, data)));
```
Comment (AlanVerbner) [inline cardano-rosetta-server/src/server/services/cardano-services.ts:791]: @jvieiro this addresses needed to be unique so I added it.. can you please create a test to validate this statement is working properly please?

Comment (jvieiro) [reply cardano-rosetta-server/src/server/services/cardano-services.ts:791]: Added at https://github.com/input-output-hk/cardano-rosetta/pull/252/files#diff-5ed14e66a15e1cf387817c03abbbea2495c0758c58a20bed29e75e9d859e304cR77

**Review by AlanVerbner — CHANGES_REQUESTED** [review]
Let's not merge this as it might not be the final fix. There is another issue.

**Review by AlanVerbner — APPROVED** [review]
